site_name: commitlint-config Documentation
theme: "material"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: "#087da1"
    accent: "#00a889"
  font:
    text: "Source Sans Pro"

repo_name: "infosisarg/commitlint-config"
repo_url: "https://github.com/infosisarg/commitlint-config"
copyright: 'Copyright Â© 2021 <a href="https://infosisglobal.com">infosisglobal</a>'

google_analytics:
  - ""
  - "auto"
